version: "3"

services:
  webserver:
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - flask
    links:
      - flask
  flask:
    build: ./app/
    ports:
      - "5000:5000"
    environment:
      - "DATABASE_URL=mysql+pymysql://root:root-password@database:3306/firewagon"
      - "FLASK_APP=application/"
      - "FLASK_ENV=development"
      - "FLASK_RUN_HOST=0.0.0.0"
    depends_on:
      - database
    links:
      - database
    restart: on-failure
  database:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=firewagon