version: "3"

services:
  webserver:
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    links:
      - flask
  flask:
    build: ./app/
    restart: on-failure
    links:
      - database
    depends_on:
      - database
  database:
    image: mariadb
    ports:
      - "3306:3306"
    restart: on-failure
    environment:
      - MYSQL_USER=root
      - MYSQL_PASSWORD=root-password
      - MYSQL_ROOT_PASSWORD=root-password
      - MYSQL_DATABASE=firewagon